### ISSUE TITLE
Intellij doesn't work with the plugin 

### ISSUE THREAD

**Issue by kell18** [sbt/sbt-avro#125]
Hello, thank you for the lib!

Using latest version of sbt-avo and avro-compile:
1. If I compile clean (no targets) project in Intellij it complains that Avro-generated classes are not found
2. If I first run `avroGenerate` then compile in Intellij - it complains that Avro-generated classes are defined 2 times

Any ideas how to solve that?
Thank you!

**Comment by RustedBones** [comment]
Hi @kell18 
Yes, this is a known issue with IntelliJ. I don't know why, bust some target folders are marked as source several times by the IDE when importing.

You can solve the issue by manually unmarking the folder like this
![image](https://user-images.githubusercontent.com/2845540/179953041-81c56f53-a9e2-4be8-8d05-1757cac5787c.png)

**Comment by RustedBones** [comment]
Or in the `File > Project Structure` setting.
Look for folders imported twice or on the same path

![image](https://user-images.githubusercontent.com/2845540/179953480-eeec4a75-1058-4b72-b26f-4bace6842205.png)

**Comment by kell18** [comment]
Thank you very much for the quick reply! 
It works now (even tho you have to un-mark those folders after every sbt reload).

**Comment by RustedBones** [comment]
Yes, unfortunately.
I'll keep the issue open and try to investigate on it when I'll have time

**Comment by RustedBones** [comment]
I think the problem comes from `sourceManaged`:
`sourceManaged` is added in the [managedSourceDirectories](https://github.com/sbt/sbt/blob/2fc446b3954057267bd4e762b5b92a0a942290e9/main/src/main/scala/sbt/Defaults.scala#L596) in both configs. So we have
```sh
sbt> show sourceDirectories
[info] * project/src/main/scala
[info] * project/src/main/java
[info] * project/target/scala-2.12/src_managed/main
```

The sbt plugin is adding a new directory: `project/target/scala-2.12/src_managed/main/compiled_avro`
This causes issue in IntelliJ.

IMHO, we should generate the sources either:
- in the default directory `project/target/scala-2.12/src_managed/main`
- in another directory like `project/target/scala-2.12/src_managed/compiled_avro/main/`

I tend to prefer the 2nd option in case other generators have conflicting file naming
