### ISSUE TITLE
Cut new release from 1.4 branch

### ISSUE THREAD

**Issue by benmccann** [sbt/sbt-avro#25]
@cavorite thank you so much for merging my PR. Would either you or @orphean-zz be able to cut a new release from the 1.4 branch?

**Comment by cavorite** [comment]
It turns out that the we repository that I was using  (repo.scala-sbt.org) is offline and we have to use Bintray now. 

I tried to follow the instructions (http://www.scala-sbt.org/release/docs/Bintray-For-Plugins.html), but I got an error updating the plugin config files (I'm a bit rusty in Scala and it seems that many things have changed in sbt). Anyway, I'm going to try again during the weekend and I'll let you know if I'm able to publish a new version.

**Comment by benmccann** [comment]
Before cutting a release, please take a look at https://github.com/sbt/sbt-avro/issues/26

I'd like to suggest we rename from sbt-plugin to sbt-plugin-1.7 and also release an sbt-plugin-1.4

**Comment by cavorite** [comment]
Feel free to rename the plugin (or create 2 versions). I'm not actively working on anything related to Scala and Avro, so I don't have a strong opinion about the issue.

**Comment by benmccann** [comment]
Thanks. I created two branches. 1.7 on master and a 1.4 branch

I think the Bintray docs you pointed to are a bit outdated. You might have better luck following the bintray plugin readme https://github.com/softprops/bintray-sbt

I installed the Bintray plugin on both branches. Not sure I have set all the settings you need, but at least it's a start

**Comment by benmccann** [comment]
@cavorite were you by chance able to look at this over the weekend? let me know if there's anything i can do to help

**Comment by cavorite** [comment]
No, I haven't tried. If you have experience with bintray, I would
appreciate if you can try to configure a repository for both packages.

**Comment by benmccann** [comment]
Ok, I think I was able to get it published. https://bintray.com/sbt/sbt-plugin-releases/sbt-avro-1.4/1.1.0#files/com.cavorite/sbt-avro-1-4/scala_2.10/sbt_0.13/1.1.0

thanks!

**Comment by cavorite** [comment]
Thanks @benmccann!
